name: Android CI

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./client
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: ./gradlew test
  # android_tests:
  #   runs-on: macos-11.0
  #   defaults:
  #     run:
  #       working-directory: ./client
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run instrumentation tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: 29
  #         script: ./gradlew connectedAndroidTest